name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Semantic Version Type
        options:
          - major
          - minor
          - patch
          - revision

      pre_release:
        type: choice
        description: Pre Rlease?
        options:
          - stable
          - alpha
          - beta
          - rc

      dry_run:
        type: boolean
        description: Dry Run?
        default: false

jobs:
    call-workflow-in-another-repo:
      uses: neolution-ch/neolution-reusable-workflows/.github/workflows/release-it-yarn-npm.yml@1d4b9a1364fb86a59e50d12d9038a19ff52d39b0
      with:
        dry-run: ${{ github.event.inputs.dry_run }}
        version-type: ${{ github.event.inputs.version_type }}
        pre-release-channel: ${{ github.event.inputs.pre_release }}
      secrets:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        npm-token: "dry run does not require npm token"
        release-bot-app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
        release-bot-app-private-key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY }}